docker run -it -d \
  --label traefik.http.routers.luhanga.rule=Host\(\`luhangacredit.loan-pocket.com\`\) \
  --label traefik.http.routers.luhanga.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.luhanga.tls=true \
  --label traefik.http.routers.luhanga.service=luhanga-credit-http \
  --label traefik.http.services.luhanga-credit-http.loadbalancer.server.port=80 \
  --name luhanga_credit \
  --network web \
  --restart always \
  --expose 80 \
   emasanga/mikoposoft_nack:may19